const Program = require('../models/Program');

// @desc    Get all programs
// @route   GET /api/admin/programs
// @access  Public
const getPrograms = async (req, res) => {
    const programs = await Program.find();

    const formattedPrograms = programs.map(p => ({
        id: p.programId, // Use the auto-incremented ID
        _id: p._id, // Keep _id just in case, but 'id' is what usually binds to UI keys/display
        title: p.title,
        description: p.description,
        startDate: p.startDate,
        endDate: p.endDate,
        orientationDate: p.orientationDate,
        orientationTime: p.orientationTime,
        orientationLocation: p.orientationLocation,
        orientationLink: p.orientationLink,
        orientationAgenda: p.orientationAgenda,
    }));
    res.status(200).json(formattedPrograms);
};

// @desc    Create a program
// @route   POST /api/admin/programs
// @access  Private/Admin
const createProgram = async (req, res) => {
    const { title, description, startDate, endDate } = req.body;

    if (!title || !description || !startDate || !endDate) {
        return res.status(400).json({ message: 'Please add all fields' });
    }

    const program = await Program.create({
        title,
        description,
        startDate,
        endDate,
        orientationDate: req.body.orientationDate,
        orientationTime: req.body.orientationTime,
        orientationLocation: req.body.orientationLocation,
        orientationLink: req.body.orientationLink,
        orientationAgenda: req.body.orientationAgenda,
    });

    // programId is generated by pre-save hook
    res.status(201).json({
        id: program.programId,
        _id: program._id,
        title: program.title,
        description: program.description,
        startDate: program.startDate,
        endDate: program.endDate,
        orientationDate: program.orientationDate,
        orientationTime: program.orientationTime,
        orientationLocation: program.orientationLocation,
        orientationLink: program.orientationLink,
        orientationAgenda: program.orientationAgenda,
    });
};

// @desc    Update a program
// @route   PUT /api/admin/programs/:id
// @access  Private/Admin
const updateProgram = async (req, res) => {
    // Try to find by programId (number) first
    let query = { programId: req.params.id };

    // If id is not a number, maybe it's _id? But simplifying to programId for consistency with frontend using .id

    const program = await Program.findOne(query);

    if (!program) {
        return res.status(404).json({ message: 'Program not found' });
    }

    const updatedProgram = await Program.findOneAndUpdate(query, req.body, {
        new: true,
    });

    res.status(200).json({
        id: updatedProgram.programId,
        title: updatedProgram.title,
        description: updatedProgram.description,
        startDate: updatedProgram.startDate,
        endDate: updatedProgram.endDate,
        orientationDate: updatedProgram.orientationDate,
        orientationTime: updatedProgram.orientationTime,
        orientationLocation: updatedProgram.orientationLocation,
        orientationLink: updatedProgram.orientationLink,
        orientationAgenda: updatedProgram.orientationAgenda,
    });
};

// @desc    Delete a program
// @route   DELETE /api/admin/programs/:id
// @access  Private/Admin
const deleteProgram = async (req, res) => {
    const program = await Program.findOne({ programId: req.params.id });

    if (!program) {
        return res.status(404).json({ message: 'Program not found' });
    }

    await program.deleteOne();

    res.status(200).json({ id: req.params.id });
};

module.exports = {
    getPrograms,
    createProgram,
    updateProgram,
    deleteProgram,
};
